- name: find latest AMI for server
  ec2_ami_info:
    owners: "amazon"
    filters:
      architecture: "x86_64"
      name: "amzn-ami-hvm-2018.03.*-x86_64-gp2"
  register: ami_asg
- name: now get the latest one
  set_fact:
    latest_ami: >
      {{ ami_asg.images | sort(attribute='creation_date') | last }}